services:
  qyt-psql:
    environment:
      - POSTGRES_PASSWORD=Cisco0123
    image: "postgres:13.7"
    ports:
      - "5432:5432"
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      - psql

networks:
  psql:
    driver: bridge